spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nailsalon
    username: nailsalon
    password: nailsalon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
